name: MAIN Workflow

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run-tests:
    uses: kirandevops1993/VS-TEST-REUSABLE/.github/workflows/VStest-reusable.yml@main
    with:
      dotnet-version: "7.0.x"
      test-assembly: "**/*Tests.dll"
      test-filter-criteria: "TestCategory=Unit"
      code-coverage-enabled: true
      configuration: "Release"
      platform: "x64"
      test-run-title: "Unit Tests"
      custom-test-adapters: "path/to/custom/adapters"
      run-in-parallel: true
      testPlan: "Plan1"
      testSuite: "SuiteA"
      testConfiguration: "DebugConfig"
      tcmTestRun: "1234"
      uiTests: false
      vsTestVersion: "latest"
      vstestLocation: "C:/vstest.console.exe"
      otherConsoleOptions: "--verbosity normal"
      diagnosticsEnabled: true
      collectDumpOn: "onAbortOnly"
      rerunFailedTests: true
      rerunType: "specific"
      rerunMaxAttempts: "3"
      dontDistribute: false
