name: Main Workflow
on:
  push:
    branches:
      - main
jobs:
  run-tests:
    uses: kirandevops1993/VS-TEST-REUSABLE/.github/workflows/VStest-reusable.yml@main
    with:
      dotnet-version: "7.0.x"
      test-assembly: "**/*Tests.dll"
      test-filter-criteria: "TestCategory=Unit"
      run-settings-file: "test.runsettings"
      code-coverage-enabled: true
      configuration: "Release"
      platform: "x64"
      test-run-title: "Unit Tests"
      custom-test-adapters: "path/to/custom/adapters"
      run-in-parallel: true
      testPlan: "Plan1"
      testSuite: "SuiteA"
      testConfiguration: "DebugConfig"
      tcmTestRun: "1234"
      runOnlyImpactedTests: true
      runAllTestsAfterXBuilds: "50"
      uiTests: false
      vstestLocationMethod: "version"
      vsTestVersion: "latest"
      vstestLocation: "C:/vstest.console.exe"
      overrideTestrunParameters: "Param1=Value1"
      otherConsoleOptions: "--verbosity normal"
      diagnosticsEnabled: true
      collectDumpOn: "onAbortOnly"
      rerunFailedTests: true
      rerunType: "basedOnTestFailurePercentage"
      rerunFailedThreshold: "30"
      rerunFailedTestCasesMaxLimit: "5"
      rerunMaxAttempts: "3"
      distributionBatchType: "basedOnTestCases"
      batchingBasedOnAgentsOption: "autoBatchSize"
      customBatchSizeValue: "10"
      batchingBasedOnExecutionTimeOption: "autoBatchSize"
      customRunTimePerBatchValue: "60"
      dontDistribute: false
      publishRunAttachments: true
      donotPublishTestResults: false
      failOnMinTestsNotRun: false
      minimumExpectedTests: "1"

just REMOVE test.runsettings & run-settings-file  from bomain & reusable workflows  & give updated workflows. remainging keep as it is 

Updated Reusable Workflow
yaml

name: VSTest Reusable Workflow

on:
  workflow_call:
    inputs:
      dotnet-version:
        required: true
        type: string
      test-assembly:
        required: true
        type: string
      test-filter-criteria:
        required: false
        type: string
      configuration:
        required: true
        type: string
      platform:
        required: false
        type: string
      code-coverage-enabled:
        required: false
        type: boolean
      test-run-title:
        required: false
        type: string
      custom-test-adapters:
        required: false
        type: string
      run-in-parallel:
        required: false
        type: boolean
      testPlan:
        required: false
        type: string
      testSuite:
        required: false
        type: string
      testConfiguration:
        required: false
        type: string
      tcmTestRun:
        required: false
        type: string
      runOnlyImpactedTests:
        required: false
        type: boolean
      runAllTestsAfterXBuilds:
        required: false
        type: string
      uiTests:
        required: false
        type: boolean
      vstestLocationMethod:
        required: false
        type: string
      vsTestVersion:
        required: false
        type: string
      vstestLocation:
        required: false
        type: string
      overrideTestrunParameters:
        required: false
        type: string
      otherConsoleOptions:
        required: false
        type: string
      diagnosticsEnabled:
        required: false
        type: boolean
      collectDumpOn:
        required: false
        type: string
      rerunFailedTests:
        required: false
        type: boolean
      rerunType:
        required: false
        type: string
      rerunFailedThreshold:
        required: false
        type: string
      rerunFailedTestCasesMaxLimit:
        required: false
        type: string
      rerunMaxAttempts:
        required: false
        type: string
      distributionBatchType:
        required: false
        type: string
      batchingBasedOnAgentsOption:
        required: false
        type: string
      customBatchSizeValue:
        required: false
        type: string
      runOnlyImpactedTests0:
        required: false
        type: string
      runOnlyImpactedTests1:
        required: false
        type: string
      dontDistribute:
        required: false
        type: boolean
      runOnlyImpactedTests2:
        required: false
        type: boolean
      runOnlyImpactedTests3:
        required: false
        type: boolean
      runOnlyImpactedTests4:
        required: false
        type: boolean
      runOnlyImpactedTests5:
        required: false
        type: string

jobs:
  run-tests:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ inputs.dotnet-version }}

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build --configuration ${{ inputs.configuration }} --no-restore

      - name: Run tests
        run: |
          dotnet test `
            --configuration "${{ inputs.configuration }}" `
            --logger "trx" `
            --results-directory "TestResults" `
            ${{ inputs.code-coverage-enabled && '--collect:"XPlat Code Coverage"' '' }} `
            ${{ inputs.test-filter-criteria && format('--filter "{0}"', inputs.test-filter-criteria) '' }} `
            ${{ inputs.custom-test-adapters && format('--TestAdapterPath "{0}"', inputs.custom-test-adapters) '' }} `
            ${{ inputs.run-in-parallel && '--parallel' '' }} `
            ${{ inputs.test-run-title && format('--testRunTitle "{0}"', inputs.test-run-title) '' }} `
            ${{ inputs. runOnlyImpactedTests && '-- runOnlyImpactedTests' '' }} `
            ${{ inputs.uiTests && '--uiTests' '' }} `
            ${{ inputs. vstestLocationMethod && format('-- vstestLocationMethod "{0}"', inputs. vstestLocationMethod) '' }} `
            ${{ inputs.vsTestVersion && format('--vsTestVersion "{0}"', inputs.vsTestVersion) '' }} `
            ${{ inputs.vstestLocation && format('--vstestLocation "{0}"', inputs.vstestLocation) '' }} `
            ${{ inputs. overrideTestrunParameters && format('-- overrideTestrunParameters "{0}"', inputs. overrideTestrunParameters) '' }} `
            ${{ inputs.otherConsoleOptions '' }} `
            ${{ inputs.diagnosticsEnabled && '--diagnosticsEnabled' '' }} `
            ${{ inputs.collectDumpOn && format('--collectDumpOn "{0}"', inputs.collectDumpOn) '' }} `
            ${{ inputs.rerunFailedTests && '--rerunFailedTests' '' }} `
            ${{ inputs.rerunType && format('--rerunType "{0}"', inputs.rerunType) '' }} `
            ${{ inputs. rerunFailedThreshold && format('-- rerunFailedThreshold "{0}"', inputs. rerunFailedThreshold) '' }} `
            ${{ inputs. rerunFailedTestCasesMaxLimit && format('-- rerunFailedTestCasesMaxLimit "{0}"', inputs. rerunFailedTestCasesMaxLimit) '' }} `
            ${{ inputs.rerunMaxAttempts && format('--rerunMaxAttempts "{0}"', inputs.rerunMaxAttempts) '' }} `
            ${{ inputs. distributionBatchType && format('-- distributionBatchType "{0}"', inputs. distributionBatchType) '' }} `
            ${{ inputs. batchingBasedOnAgentsOption && format('-- batchingBasedOnAgentsOption "{0}"', inputs. batchingBasedOnAgentsOption) '' }} `
            ${{ inputs. customBatchSizeValue && format('-- customBatchSizeValue "{0}"', inputs. customBatchSizeValue) '' }} `
            ${{ inputs. runOnlyImpactedTests0 && format('-- runOnlyImpactedTests0 "{0}"', inputs. runOnlyImpactedTests0) '' }} `
            ${{ inputs. runOnlyImpactedTests1 && format('-- runOnlyImpactedTests1 "{0}"', inputs. runOnlyImpactedTests1) '' }} `
            ${{ inputs.dontDistribute && '--dontDistribute' '' }} `
            ${{ inputs. runOnlyImpactedTests2 && '-- runOnlyImpactedTests2' '' }} `
            ${{ inputs. runOnlyImpactedTests3 && '-- runOnlyImpactedTests3' '' }} `
            ${{ inputs. runOnlyImpactedTests4 && '-- runOnlyImpactedTests4' '' }} `
            ${{ inputs. runOnlyImpactedTests5 && format('-- runOnlyImpactedTests5 "{0}"', inputs. runOnlyImpactedTests5) '' }}
